#!/system/bin/sh

bbox=/sbin/busybox

# init.d support
if [ ! -e /system/etc/init.d ] ; then
  $bbox mount -o remount,rw /system
  $bbox mkdir /system/etc/init.d
  $bbox chown -R root.root /system/etc/init.d
  $bbox chmod -R 755 /system/etc/init.d
  $bbox mount -o remount,ro /system
fi

# execute init.d scripts
$bbox run-parts /system/etc/init.d



